# Generated by Django 5.1.1 on 2024-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_datoscrawler_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscrawler',
            name='valor',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
