# Generated by Django 5.1.1 on 2024-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_datoscrawler_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscrawler',
            name='valor',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
