# Generated by Django 5.1.1 on 2024-10-05 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_datoscrawler_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscrawler',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
